"""
🧠 ReflexArc Thinker Agent — ADK Agent Definition

The Thinker is a structured, comparative reasoner. It takes evolution strategies
(potentially those generated by the Dreamer or sourced from AI research) and
*evaluates them against each other*, selecting the best candidate for
the current ReflexArc implementation cycle and producing a concrete action plan.

Available standalone via `adk web` at http://localhost:8000
Also runs as part of the EvolutionSwarm during Dream Cycle Phase 5.
"""

import json
import os
from pathlib import Path

from google.adk.agents import LlmAgent


# ─── Live context loaders ──────────────────────────────

def _load_system_metrics() -> str:
    """Load recent system metrics to ground the Thinker's recommendations."""
    try:
        # Try to read the latest dream journal for performance data
        journal_dir = Path("memory/dream_journal")
        if journal_dir.exists():
            entries = sorted(journal_dir.glob("*.md"), reverse=True)
            if entries:
                content = entries[0].read_text(encoding="utf-8")[:1500]
                # Extract metrics section if present
                if "Metrics" in content or "metric" in content.lower():
                    return content
        return "No recent metrics available."
    except Exception:
        return "Could not load system metrics."


def _load_implemented_proposals() -> str:
    """Provide the Thinker with history of what has already been tried."""
    try:
        qfile = Path("memory/proposal_queue.json")
        if not qfile.exists():
            return "No proposal history yet."
        with open(qfile) as f:
            queue = json.load(f)
        implemented = [p for p in queue if p.get("status") in ("implemented", "failed")]
        if not implemented:
            return "No proposals have been implemented yet."
        lines = []
        for p in implemented[-10:]:
            status = p.get("status", "unknown")
            icon = "✅" if status == "implemented" else "❌"
            lines.append(f"{icon} [{status}] {p.get('content','')[:80]}")
        return "\n".join(lines)
    except Exception:
        return "Could not load proposal history."


def _load_error_rate() -> str:
    """Give Thinker a sense of system health."""
    try:
        efile = Path("memory/error_tasks.json")
        if not efile.exists():
            return "No error data."
        with open(efile) as f:
            errors = json.load(f)
        critical = [e for e in errors if e.get("severity") in ("critical", "error")]
        return (
            f"{len(errors)} total logged errors, "
            f"{len(critical)} critical/error severity."
        )
    except Exception:
        return "Could not load error data."


SYSTEM_METRICS = _load_system_metrics()
IMPLEMENTED_PROPOSALS = _load_implemented_proposals()
ERROR_RATE = _load_error_rate()

# ─── Thinker Agent ────────────────────────────────────

root_agent = LlmAgent(
    name="Thinker",
    description=(
        "A structured analytical AI for ReflexArc. "
        "Evaluates competing AI evolution strategies, scores them against each other, "
        "selects the single best next step for the current system state, "
        "and produces a concrete, executable implementation plan."
    ),
    instruction=f"""You are the **Thinker** — the analytical, decision-making mind of ReflexArc.

Your job is to take evolution proposals (from the Dreamer, the user, or prior sessions) and:
1. **Evaluate** each one against clear criteria
2. **Compare** them systematically  
3. **Select** the single best proposal to implement RIGHT NOW given the system's current state
4. **Produce** a concrete, step-by-step implementation plan

### Evaluation Criteria (score each 1-5)
- **Impact** — How much will this improve ReflexArc's autonomy, resilience, or capability?
- **Feasibility** — Can this be implemented within the current Python/aiohttp/ADK stack?
- **Risk** — Could this break existing functionality? (lower = better)
- **Urgency** — Does current system state make this immediately important?

### Current System State
**Error profile:** {ERROR_RATE}

**Recent metrics:**
{SYSTEM_METRICS}

**Already implemented / failed proposals:**
{IMPLEMENTED_PROPOSALS}

### Your Output Format

First, show a **comparison table** of all proposals you are evaluating:

| Proposal | Impact | Feasibility | Risk | Urgency | Total |
|----------|--------|-------------|------|---------|-------|
| ...      | /5     | /5          | /5   | /5      | /20   |

Then output the **selected winner**:

#### 🏆 Selected for Implementation: [Proposal Name]
**Why selected:** 1-2 sentences.
**Implementation plan:**
1. File: `path/to/file.py` — what to change
2. File: `path/to/other.py` — what to change
**Expected outcome:** What will be measurably different after this is implemented.
**Rollback plan:** How to revert if it breaks something.

Be decisive. Always select exactly one proposal. The system cannot implement two things at once.""",
)
