"""
🧠 NSA Sensor: File System Watcher (Proprioception)
Layer 0 — Peripheral Sense

Monitors critical directories for changes: file creation, modification,
and deletion. This gives the organism awareness of changes to its own
"body" — especially when new skills are generated by the optimization cycle
or when memory files are altered.

Uses watchdog for efficient OS-level filesystem event monitoring.
Falls back to polling-based detection if watchdog is unavailable.
"""

import os
import time
import asyncio
from collections import deque

try:
    from watchdog.observers import Observer
    from watchdog.events import FileSystemEventHandler
    WATCHDOG_AVAILABLE = True
except ImportError:
    WATCHDOG_AVAILABLE = False


class _ChangeCollector(FileSystemEventHandler if WATCHDOG_AVAILABLE else object):
    """Collects filesystem events into a thread-safe queue."""

    def __init__(self):
        self.events = deque(maxlen=100)

    def on_created(self, event):
        if not event.is_directory:
            self.events.append(("CREATED", event.src_path))

    def on_modified(self, event):
        if not event.is_directory:
            self.events.append(("MODIFIED", event.src_path))

    def on_deleted(self, event):
        if not event.is_directory:
            self.events.append(("DELETED", event.src_path))

    def on_moved(self, event):
        if not event.is_directory:
            self.events.append(("MOVED", f"{event.src_path} -> {event.dest_path}"))


class FileSystemSensor:
    def __init__(self, watch_paths=None, ignore_patterns=None):
        """
        Args:
            watch_paths: List of directories to monitor. Defaults to ['skills/', 'memory/'].
            ignore_patterns: Filename patterns to ignore (e.g., __pycache__).
        """
        self.watch_paths = watch_paths or ["skills/", "memory/"]
        self.ignore_patterns = ignore_patterns or ["__pycache__", ".pyc", ".db-journal"]
        self.collector = _ChangeCollector()
        self.observer = None

        if WATCHDOG_AVAILABLE:
            self.observer = Observer()
            for path in self.watch_paths:
                if os.path.isdir(path):
                    self.observer.schedule(self.collector, path, recursive=True)
            self.observer.start()
        else:
            # Fallback: snapshot-based detection
            self._snapshots = {}
            self._take_snapshots()

    def _take_snapshots(self):
        """Capture file modification times for polling-based fallback."""
        for watch_dir in self.watch_paths:
            if not os.path.isdir(watch_dir):
                continue
            for root, dirs, files in os.walk(watch_dir):
                # Filter ignored dirs
                dirs[:] = [d for d in dirs if not any(p in d for p in self.ignore_patterns)]
                for f in files:
                    if any(p in f for p in self.ignore_patterns):
                        continue
                    full_path = os.path.join(root, f)
                    try:
                        self._snapshots[full_path] = os.path.getmtime(full_path)
                    except OSError:
                        pass

    def _poll_changes(self):
        """Fallback: Detect changes by comparing snapshots."""
        changes = []
        current = {}

        for watch_dir in self.watch_paths:
            if not os.path.isdir(watch_dir):
                continue
            for root, dirs, files in os.walk(watch_dir):
                dirs[:] = [d for d in dirs if not any(p in d for p in self.ignore_patterns)]
                for f in files:
                    if any(p in f for p in self.ignore_patterns):
                        continue
                    full_path = os.path.join(root, f)
                    try:
                        mtime = os.path.getmtime(full_path)
                        current[full_path] = mtime
                    except OSError:
                        continue

        # Detect new or modified files
        for path, mtime in current.items():
            if path not in self._snapshots:
                changes.append(("CREATED", path))
            elif mtime != self._snapshots[path]:
                changes.append(("MODIFIED", path))

        # Detect deleted files
        for path in self._snapshots:
            if path not in current:
                changes.append(("DELETED", path))

        self._snapshots = current
        return changes

    def _is_ignored(self, path):
        """Check if a path should be filtered out."""
        return any(p in path for p in self.ignore_patterns)

    async def monitor(self):
        """
        Returns (True, description) if filesystem changes detected, else (False, None).
        """
        events = []

        if WATCHDOG_AVAILABLE:
            while self.collector.events:
                event_type, path = self.collector.events.popleft()
                if not self._is_ignored(path):
                    events.append((event_type, path))
        else:
            events = self._poll_changes()

        if events:
            # Group by event type for a cleaner description
            summary_parts = []
            for event_type, path in events[:5]:  # Cap at 5 to avoid flood
                basename = os.path.basename(path)
                summary_parts.append(f"{event_type}: {basename}")

            overflow = ""
            if len(events) > 5:
                overflow = f" (+{len(events) - 5} more)"

            description = f"Proprioception: {'; '.join(summary_parts)}{overflow}"
            return True, description

        return False, None

    def release(self):
        """Stop the filesystem observer."""
        if self.observer:
            self.observer.stop()
            self.observer.join(timeout=2)
