"""
📝 ReflexArc Changes Logger

Utility for writing structured change events to memory/agent_logs/changes_log.jsonl.
Used by the Dream Engine, skills, and any module that creates or modifies files.

Usage:
    from utils.changes_logger import log_change

    log_change(
        change_type="skill_added",
        file="skills/auto_cpu_alert.py",
        description="Auto-generated by Dream Engine for CPU spike pattern",
        author="dream_engine"
    )

Change types:
  - skill_added     : A new .py skill was created in skills/
  - code_modified   : An existing file was modified
  - proposal_saved  : An LLM-generated proposal was written to disk
  - config_changed  : A config file was updated
"""

import json
import time
from datetime import datetime
from pathlib import Path
from typing import Optional


CHANGES_LOG_PATH = Path("memory/agent_logs/changes_log.jsonl")


def log_change(
    change_type: str,
    file: str,
    description: str,
    author: str = "system",
    extra: Optional[dict] = None,
) -> None:
    """
    Append a structured change record to the changes log.

    Args:
        change_type: Category of change (e.g. 'skill_added', 'code_modified')
        file: Relative path of the file created or modified
        description: Human-readable description of what changed and why
        author: Which component made the change (e.g. 'dream_engine', 'user')
        extra: Optional dict of additional metadata to include
    """
    try:
        CHANGES_LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
        entry = {
            "timestamp": datetime.now().isoformat(),
            "unix_ts": time.time(),
            "type": change_type,
            "file": file,
            "description": description,
            "author": author,
        }
        if extra:
            entry["extra"] = extra

        with open(CHANGES_LOG_PATH, "a") as f:
            f.write(json.dumps(entry) + "\n")
    except Exception:
        pass  # Never let logging crash the caller


def read_changes(limit: int = 50, change_type: Optional[str] = None) -> list:
    """
    Read recent change log entries.

    Args:
        limit: Maximum number of entries to return (most recent first)
        change_type: Optional filter by change type

    Returns:
        List of change entry dicts
    """
    try:
        if not CHANGES_LOG_PATH.exists():
            return []
        entries = []
        with open(CHANGES_LOG_PATH, "r") as f:
            lines = f.readlines()

        for line in reversed(lines):
            if change_type is not None and f'"{change_type}"' not in line:
                continue
            try:
                entry = json.loads(line.strip())
                if change_type is None or entry.get("type") == change_type:
                    entries.append(entry)
                    if len(entries) == limit:
                        break
            except json.JSONDecodeError:
                continue
        entries.reverse()
        return entries
    except Exception:
        return []
