"""
🗂️ ReflexArc Proposal Queue Manager

Manages the lifecycle of evolution proposals generated by the ADK swarm:
1. **De-duplication**: Filters semantically similar proposals before adding to queue
2. **Queueing**: Persists proposals as a JSON queue with status tracking
3. **Implementation**: Picks up the next pending proposal and attempts to apply it

Queue states:
  pending     → Not yet implemented, waiting for next dream cycle
  in_progress → Currently being implemented (or last attempt failed mid-way)
  implemented → Successfully applied to codebase
  failed      → Could not be auto-applied, needs human review
  rejected    → Duplicate of an existing proposal, discarded
"""

import json
import os
import re
import time
from datetime import datetime
from pathlib import Path
from typing import List, Dict, Any, Optional

QUEUE_FILE = Path("memory/proposal_queue.json")
SIMILARITY_THRESHOLD = 0.6   # Two proposals are "same" if >60% word overlap


# ─── Core Queue Operations ────────────────────────────────────

def load_queue() -> List[Dict[str, Any]]:
    """Load the proposal queue from disk."""
    if not QUEUE_FILE.exists():
        return []
    try:
        with open(QUEUE_FILE, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return []


def save_queue(queue: List[Dict[str, Any]]) -> None:
    """Persist the proposal queue to disk."""
    QUEUE_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(QUEUE_FILE, "w") as f:
        json.dump(queue, f, indent=2)


def _text_similarity(a: str, b: str) -> float:
    """Compute Jaccard similarity between two text strings (word sets)."""
    words_a = set(re.findall(r'\w+', a.lower()))
    words_b = set(re.findall(r'\w+', b.lower()))
    if not words_a or not words_b:
        return 0.0
    return len(words_a & words_b) / len(words_a | words_b)


def enqueue_proposals(new_proposals: List[Dict[str, Any]]) -> Dict[str, int]:
    """
    Add new proposals to the queue, deduplicating against existing entries.

    Args:
        new_proposals: List of dicts with keys: agent, content, date

    Returns:
        Summary dict with counts: added, duplicates_skipped
    """
    queue = load_queue()
    existing_content = [p["content"] for p in queue if p["status"] != "rejected"]

    added = 0
    skipped = 0

    for proposal in new_proposals:
        content = proposal.get("content", "")
        if not content.strip():
            continue

        # Check for duplicates by similarity
        is_duplicate = any(
            _text_similarity(content, existing) >= SIMILARITY_THRESHOLD
            for existing in existing_content
        )

        if is_duplicate:
            skipped += 1
            continue

        entry = {
            "id": f"prop_{int(time.time() * 1000)}_{added}",
            "agent": proposal.get("agent", "unknown"),
            "content": content,
            "added_at": datetime.now().isoformat(),
            "status": "pending",
            "attempts": 0,
            "implementation_notes": None,
        }
        queue.append(entry)
        existing_content.append(content)
        added += 1

    save_queue(queue)
    return {"added": added, "duplicates_skipped": skipped}


def next_pending() -> Optional[Dict[str, Any]]:
    """Return the oldest pending proposal without modifying the queue."""
    queue = load_queue()
    for proposal in queue:
        if proposal["status"] == "pending":
            return proposal
    return None


def mark_proposal(proposal_id: str, status: str, notes: str = "") -> None:
    """Update the status of a proposal by ID."""
    queue = load_queue()
    for p in queue:
        if p["id"] == proposal_id:
            p["status"] = status
            p["implementation_notes"] = notes
            p["updated_at"] = datetime.now().isoformat()
            break
    save_queue(queue)


def queue_stats() -> Dict[str, int]:
    """Return counts by status."""
    queue = load_queue()
    stats: Dict[str, int] = {}
    for p in queue:
        stats[p["status"]] = stats.get(p["status"], 0) + 1
    return stats


# ─── Implementation Attempt ───────────────────────────────────

def attempt_implementation(proposal: Dict[str, Any], router) -> str:
    """
    Ask the LLM to parse and apply the proposal as a code patch.
    Returns a summary of what was done.
    """
    content = proposal["content"]

    # Build a structured prompt asking the model to extract and apply the patch
    prompt = (
        "You are an autonomous code patch agent for the ReflexArc AI system.\n\n"
        "You have been given an evolution proposal from a previous analysis run:\n\n"
        f"--- PROPOSAL ---\n{content[:3000]}\n--- END PROPOSAL ---\n\n"
        "Your task:\n"
        "1. Extract any concrete code change described (file path + code snippet).\n"
        "2. If a clear, safe, single-file python patch can be extracted, output ONLY:\n"
        "   FILE: <relative_file_path>\n"
        "   ```python\n"
        "   <full modified function or class>\n"
        "   ```\n"
        "3. If the proposal is architectural advice with no concrete python code, output:\n"
        "   ADVISORY: <one sentence summary>\n"
        "4. If unsafe, speculative, or multi-file, output:\n"
        "   SKIP: <reason>\n"
        "CRITICAL INSTRUCTION: You MUST output exactly one of the three formats above (FILE, ADVISORY, or SKIP). NEVER output an empty string or conversational text."
    )

    try:
        response = router.route(
            tier="cortex",
            model_override=["gpt-5-codex", "gpt-5", "gpt-4o", "gpt-4"],
            messages=[
                {"role": "system", "content": "You are a precise code patch extractor. Output only the format requested."},
                {"role": "user", "content": prompt},
            ],
        )
        output = response.content.strip()
    except Exception as e:
        return f"SKIP: Router error: {e}"

    # Parse the structured response
    file_match = re.search(r'FILE:\s*([^\n]+)', output)
    
    if file_match:
        file_path = file_match.group(1).strip()
        
        # Try to extract just the python code block
        code_match = re.search(r'```(?:python)?\n?(.*?)\n?```', output, re.DOTALL)
        if code_match:
            code_block = code_match.group(1).strip()
        else:
            # Fallback: if no code block, just take everything after the FILE line
            lines = output.split('\n')
            code_lines = []
            capture = False
            for line in lines:
                if 'FILE:' in line:
                    capture = True
                    continue
                if capture:
                    code_lines.append(line)
            code_block = '\n'.join(code_lines).strip()

        if file_path and code_block and os.path.exists(file_path):
            # Safety: only write to files inside the project (no absolute paths)
            if ".." not in file_path and not file_path.startswith("/"):
                backup_path = file_path + ".bak"
                try:
                    # Back up original
                    with open(file_path, "r") as f:
                        original = f.read()
                    with open(backup_path, "w") as f:
                        f.write(original)

                    # Apply patch by appending the new function/class
                    # (A real system would do AST-level replacement)
                    with open(file_path, "a") as f:
                        f.write(f"\n\n# === AUTO-PATCH from EvolutionSwarm ({datetime.now().date()}) ===\n")
                        f.write(code_block + "\n")

                    from utils.changes_logger import log_change
                    log_change(
                        change_type="code_modified",
                        file=file_path,
                        description=f"Auto-patch applied from proposal {proposal['id']} by agent {proposal['agent']}",
                        author="proposal_queue",
                        extra={"proposal_id": proposal["id"], "backup": backup_path}
                    )
                    return f"APPLIED: Patched {file_path} (backup at {backup_path})"
                except Exception as e:
                    return f"FAILED: Could not write to {file_path}: {e}"
            else:
                return "SKIP: Unsafe file path (absolute or traversal)"
        else:
            return f"SKIP: File '{file_path}' not found or empty code block"

    elif "ADVISORY:" in output:
        advisory_match = re.search(r'ADVISORY:\s*(.*)', output)
        if advisory_match:
            return f"ADVISORY: {advisory_match.group(1)}"
        return output  # Just an advisory, mark as implemented with notes

    elif "SKIP:" in output:
        skip_match = re.search(r'SKIP:\s*(.*)', output)
        if skip_match:
            return f"SKIP: {skip_match.group(1)}"
        return output

    return f"SKIP: Unrecognized model output format: {output[:100]}"
